services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL:${NEXT_PUBLIC_API_URL}
volumes:
  node_modules:
